server:
  port: 8080
  servlet:
    context-path: /identity
spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/springboot"
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password: 123456
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true